[package]
name = "efficient_cube"
version = "0.1.0"
authors = ["FrankenApps"]
edition = "2018"
resolver="2"

[dependencies]
anyhow = "1.0"
bytemuck = { version = "1.4", features = [ "derive" ] }
glam = { version = "0.19.0", features = ["bytemuck"] }
env_logger = "0.9"
log = "0.4"
pollster = "0.2"
image = "0.23"
wgpu = "0.10"
winit = "0.25"

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.2"
glob = "0.3"

[[bin]]
name = "efficient_cube"
path = "src/main.rs"
