name: Rust

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update Rust to 2021 edition (will not be neede once virtual-env is deployed to GH-Actions).
      run: rustup update stable
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Build
      run: wasm-pack build --target web
    - name: Create publish folder
      run: mkdir www
    - name: Create build output folder
      run: mkdir www/pkg
    - name: Copy wasm files
      run: cp pkg/README.md www/README.md &&
           cp pkg/wgpu_shape_renderer_bg.wasm www/pkg/wgpu_shape_renderer_bg.wasm &&
           cp pkg/wgpu_shape_renderer_bg.wasm.d.ts www/pkg/wgpu_shape_renderer_bg.wasm.d.ts &&
           cp pkg/wgpu_shape_renderer.d.ts www/pkg/wgpu_shape_renderer.d.ts &&
           cp pkg/wgpu_shape_renderer.js www/pkg/wgpu_shape_renderer.js
    - name: Copy HTML template
      run: cp index.html www/index.html &&
           cp favicon.png www/favicon.png
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./www
